package contabilidad;
// Generated 23/04/2021 14:52:05 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * AsientoDet generated by hbm2java
 */
public class AsientoDet  implements java.io.Serializable {
    private int idCuenta;    
    private int idCentroCosto;
    private String descripcion;
    private String dc;
    private double valor;

    public AsientoDet() {
    }

    public int getIdCuenta() {
        return idCuenta;
    }

    public void setIdCuenta(int idCuenta) {
        this.idCuenta = idCuenta;
    }

    public int getIdCentroCosto() {
        return idCentroCosto;
    }

    public void setIdCentroCosto(int idCentroCosto) {
        this.idCentroCosto = idCentroCosto;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getDc() {
        return dc;
    }

    public void setDc(String dc) {
        this.dc = dc;
    }

    public double getValor() {
        return valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

	

}


