package contabilidad;
// Generated 23/04/2021 14:52:05 by Hibernate Tools 4.3.1



/**
 * PlantillaDet generated by hbm2java
 */
public class PlantillaDet  implements java.io.Serializable {
     private int idCuenta;
     private String cuentaNumero;
     private String cuentaNombre;
     private String dc;
     private String tieneCC;
     private String formula;

    public PlantillaDet() {
    }

    public int getIdCuenta() {
        return idCuenta;
    }

    public void setIdCuenta(int idCuenta) {
        this.idCuenta = idCuenta;
    }

    public String getCuentaNumero() {
        return cuentaNumero;
    }

    public void setCuentaNumero(String cuentaNumero) {
        this.cuentaNumero = cuentaNumero;
    }

    public String getCuentaNombre() {
        return cuentaNombre;
    }

    public void setCuentaNombre(String cuentaNombre) {
        this.cuentaNombre = cuentaNombre;
    }

    public String getDc() {
        return dc;
    }

    public void setDc(String dc) {
        this.dc = dc;
    }

    public String getTieneCC() {
        return tieneCC;
    }

    public void setTieneCC(String tieneCC) {
        this.tieneCC = tieneCC;
    }

    public String getFormula() {
        return formula;
    }

    public void setFormula(String formula) {
        this.formula = formula;
    }

	



}


